<?php

/**
 * @file
 * Contains dcp_user.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;

/**
 * Using hook_form_alter.
 */
function dcp_user_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $text = "Don't have and account ? ";
    $form['help'] = [
      '#type' => 'markup',
      '#wrapper_attributes' => ['style' => 'align-items: center'],
      '#markup' => '<div class="help"><span>' . $text . '<a href="/user/register">Sign up</a></span></div>',
      '#weight' => '100',
    ];
  }
}

/**
 * Implements hook_node_access().
 */
function dcp_user_node_access(NodeInterface $node, $op, AccountInterface $account) {
  $access = AccessResult::neutral();
  switch ($node->bundle()) {
    case 'sponsor':
      $access = _dcp_user_node_access($node, $op, $account, 'access sponsor detail page');
      break;
    case 'schedule':
      $access = _dcp_user_node_access($node, $op, $account, 'access schedule detail page');
      break;
  }

  return $access;
}

/**
 * Helper function to determine access on sponsor node.
 */
function _dcp_user_node_access(NodeInterface $node, string $op, AccountInterface $account, string $permission) {
  $current_route_node = \Drupal::routeMatch()->getParameter('node');

  if ($current_route_node->id() !== $node->id()) {
    return AccessResult::neutral();
  }

  if ($op !== 'view' || $account->hasPermission($permission)) {
    return AccessResult::neutral();
  }

  return AccessResult::forbidden();
}
