<?php

/**
 * @file
 * Contains dcp_user.module.
 */

/**
 * Using hook_form_alter.
 */
function dcp_user_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $text = "Don't have and account ? ";
    $form['help'] = [
      '#type' => 'markup',
      '#wrapper_attributes' => ['style' => 'align-items: center'],
      '#markup' => '<div class="help"><span>' . $text . '<a href="/user/register">Sign up</a></span></div>',
      '#weight' => '100',
    ];
  }
}
