smtp_on: true
smtp_host: smtpout.secureserver.net
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_autotls: false
smtp_timeout: 10
smtp_username: camp@drupalpune.in
smtp_password: ''
smtp_from: camp@drupalpune.in
smtp_fromname: 'DrupalCamp Pune'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: drupalpune12@gmail.com
smtp_reroute_address: ''
smtp_debugging: false
smtp_keepalive: false
