name: Deploy to live

on:
  push:
    tags: v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.0'
        check-latest: true

    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install dependencies
      run: composer install

    - name: Symlink files directory
      run: ln -s /var/www/html/sites/drupalpune.in/public/files files
      working-directory: web/sites/default

    - name: Deploy to Live
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.LIVE_SERVER_SSH_KEY }}
        ARGS: "-rltDzvO --delete"
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.LIVE_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.LIVE_REMOTE_USER }}
        TARGET: ${{ secrets.LIVE_REMOTE_TARGET }}
        EXCLUDE: "/**/node_modules/"

    - name: Execute post deploy commands using remote ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LIVE_REMOTE_HOST }}
        username: ${{ secrets.LIVE_REMOTE_USER }}
        key: ${{ secrets.LIVE_REMOTE_TARGET }}
        script: |
          cd ${{ secrets.LIVE_SERVER_SSH_KEY }}
          vendor/bin/drush updb
          vendor/bin/drush cr
          vendor/bin/drush cim




    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
